### ISSUE TITLE
rustw seems to depend LD_LIBRARY_PATH being set to include the rust installation

### ISSUE THREAD

**Issue by jrmuizel** [nrc/rustw#121]
Running rustw is currently a pain because you need to set LD_LIBRARY_PATH or the equivalent on OS X manually when not running in cargo.

**Comment by nrc** [comment]
This shouldn't be a problem, even when not using cargo. It is usually only a problem if you are using a custom version of rustc (or perhaps using rustup?). I run rustw without Cargo and don't need to set LD_LIBRARY_PATH.

**Comment by jrmuizel** [comment]
I'm using rustup.

**Comment by brson** [comment]
This happens because rustup has no opportunity to configure LD_LIBRARY_PATH for rustw. rustc and rustdoc don't suffer this problem because rustup is aware of them, and installs proxies to `.cargo/bin` which configures the environment for the toolchain.

Running rustw via `cargo run` will configure the environment correctly.

I can imagine creating a workaround for this issue with a `rustup create-proxy` command that just installs an arbitrary proxy into `.cargo/bin`.

**Comment by brson** [comment]
Oh hm, I didn't realize that rustw calls the rustc executable, doesn't link to rustc directly. My previous comment doesn't explain the op then.

**Comment by jrmuizel** [comment]
My rustw links against librustdoc.dylib

**Comment by nrc** [comment]
Ah, so its not the rustc executable, but rustdoc that is probably causing problems.

I would like to pull rustdoc out of tree and into a regular Cargo crate, but that is probably too long-term a solution.

**Comment by brson** [comment]
Yeah, the problem is the rustdoc dep.
