### ISSUE TITLE
rustw.out.js is 404

### ISSUE THREAD

**Issue by jrmuizel** [nrc/rustw#133]
When running all that I get is a 404 when trying to load static/rustw.out.js

**Comment by nrc** [comment]
This is probably because either webpack is not running to create rustw.out.js or the build script is not running to move it to the target directory. If the former, then you need to follow the new building instructions (https://github.com/nrc/rustw#building), you then need to run `cargo build --release` (important to do this after running webpack). I should improve the README here.

Let me know if it still has this problem after that.
